/// @file

#include "neutrino.hpp"

int main()
{
  neutrino* program         = new neutrino();                                   // The Neutrino object.
  opengl*   opengl_context  = new opengl();                                     // The OpenGL context object.
  window*   gui_window      = new window();                                     // The gui window object.
  font*     gui_font        = new font();                                       // The gui font object.
  opencl*   opencl_context  = new opencl();                                     // The OpenCL context object.
  path*     neutrino_path   = new path();                                       // The neutrino_path environmental variable.

  ascii_spin_phase = 0;                                                         // Initializing ascii_spin_phase...
  ascii_spin_n_old = 0;                                                         // Initializing ascii_spin_n_old...
  neutrino_path = get_neutrino_path();                                          // Getting NEUTRINO_PATH environmental variable...

  neutrino->init();                                                             // Initializing neutrino...
  opengl_context->init(neutrino_path);                                          // Initializing OpenGL context...
  gui_window->init(800, 600, "neutrino");                                       // Initializing gui window...
  gui_font->init();                                                             // Initializing gui font...
  opencl_context->init(gui_window->glfw_window, GPU);                           // Initializing OpenCL context...

  setup();                                                                      // Executing Neutrino "setup" function...

  while (!program->gui_window->closed())                                        // Opening window...
  {
    program->get_tic();                                                         // Getting "tic" [us]...
    loop();                                                                     // Executing Neutrino "loop" function...
    program->get_toc();                                                         // Getting "toc" [us]...
  }

  terminate();                                                                  // Terminating Neutrino application...

  return 0;
}
