/// @file

#include "opengl.hpp"
#include "opencl.hpp"
#include "utilities.hpp"
#include "program.hpp"

int main()
{
  double  tic;                                                                  // Initial loop time [us].
  double  toc;                                                                  // Final loop time [us].
  
  get_neutrino_path();                                                          // Getting Neutrino installation path...

  setup();                                                                      // Executing Neutrino "setup" function...

  while (!glfwWindowShouldClose(window))                                        // Opening window...
  {
    tic = getCPUTime();                                                         // Getting "tic" [us]...
    loop();                                                                     // Executing Neutrino "loop" function...
    toc = getCPUTime();                                                         // Getting "toc" [us]...
    ascii_spin("Action: running OpenCL program...", tic, toc);                  // Displaying loop duration [us]...
  }

  ascii_spin_stop();                                                            // Stopping loop duration display...
  terminate();                                                                  // Terminating Neutrino application...

  return 0;
}
